app.py
import os
from flask import Flask
from routes import pages
from pymongo import MongoClient
from dotenv import load_dotenv 

load_dotenv()

def create_app():
    app = Flask(__name__)  
    client = MongoClient(os.environ.get("MONGODB_URI"))
    app.db = client.get_default_database()

    app.register_blueprint(pages)
    return app

routes.py
import datetime
import uuid
from flask import Blueprint, current_app, render_template, request, redirect, url_for

pages = Blueprint("tasks", __name__, template_folder="templates", static_folder="static")


@pages.context_processor
def add_calc_date_range():
    def date_range(start:datetime.datetime):
        dates = [start + datetime.timedelta(days=diff) for diff in range(-3, 4)]
        return dates

    return {"date_range": date_range}

def today_at_midnight():
    today = datetime.datetime.today()
    return datetime.datetime(today.year, today.month, today.day)


@pages.route("/")
def index():
    date_str = request.args.get("date")
    if date_str:
        selected_date = datetime.datetime.fromisoformat(date_str)
    else:
        selected_date = today_at_midnight()

    tasks_on_date = current_app.db.tasks.find({"added": selected_date})

    completions = [
        task["task"]
        for task in current_app.db.completions.find({"date": selected_date})
    ]

    return render_template(
        "index.html", 
        tasks=tasks_on_date,     
        selected_date=selected_date,
        completions=completions,
        title="TaskNest - Home",
    )

@pages.route('/add', methods=["GET", "POST"])
def add_task():
    today =today_at_midnight()

    if request.method == "POST":
        current_app.db.tasks.insert_one(
            {"_id": uuid.uuid4().hex, "added": today, "name": request.form.get("task")}
        )

    return render_template(
        "add_task.html", 
        title="TaskNest - Add Task", 
        selected_date=today,
    )



@pages.route("/complete", methods=["POST"])
def complete():
    date_string = request.form.get("date")
    task = request.form.get("taskId")
    date = datetime.datetime.fromisoformat(date_string)
    current_app.db.completions.insert_one({"date": date, "task": task})

    return redirect(url_for("tasks.index", date=date_string))

templates/add_task.html
{% extends "layout.html" %}

{% block main_content %}

    <form class="form" method="POST">
        <textarea class="form__input" id="task" name="task" rows="3" placeholder="Add a new task"></textarea>
        <button class="form__button" type="submit">Add</button>
    </form>

{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block main_content %}
    <section class="task-list">
    {% for task in tasks %}
        {% set completed = task["_id"] in completions %}
        {% if completed %}
        <div class="task completed">
            <p class="task__name">
                {{ task["name"] }}
            </p>
            <svg class="task__icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
            </svg>
        </div>
        {% else %}
            <div class="task">
                <form method="POST" class="task__form" action="{{ url_for('tasks.complete') }}">
                    <input type="hidden" name="taskId" value="{{ task['_id'] }}" />
                    <input type="hidden" name="date" value="{{ selected_date }}" />
                    <button type="submit" class="task__button">
                        {{ task["name"] }}
                    </button>
                </form>
            </div>
        {% endif %}


    {% endfor %}
    </section>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>{{ title }}</title>
        <link href="http://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">

        {% block head_content %} {% endblock %}
    </head>

    <body>
        <header class="header">
            <h1 class="header__logo"><a href="{{ url_for('tasks.index') }}" class="header__link">Tasks</a></h1>
            {% if "add" not in request.endpoint %}
                <a href="{{ url_for('tasks.add_task') }}" class="header__link">+ Add new</a>
            {% endif %}
        </header>

        <main class="main">
            <section class="dates">
                {% for date in date_range(selected_date) %}
                    <a
                        class="dates__link {{ 'dates__link--current' if loop.index0 == 3 else ''}}" 
                        href="{{ url_for('tasks.index', date=date) }}">
                    <time class="date" datetime="{{ date }}">
                        <span>{{ date.strftime("%a") }}</span>
                        <span>{{ date.strftime("%d") }}</span>
                    </time>
                    </a>
                {% endfor %}
            </section>
        
            {% block main_content %}
            {% endblock %}
        </main>
    </body>
</html>